name: graphql_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  ferry: ^0.10.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  gql_http_link: ^0.4.0
  state_notifier: ^0.7.1


dev_dependencies:
  build_runner: ^2.1.7
  ferry_generator: ^0.4.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
